import supabase from "@/supabase";
import { NextRequest, NextResponse } from "next/server";

type CourseInfo = {
  id: number,
  title: string | null,
  badge_url: string | null,
  professor: string | null,
  first_class: string | null,
  landing_url: string | null,
  duration: number,
  created_at: string | null,
  description: string | null,
  date: string | null,
  level: string | null,
  practice_time: number,
  opinions_link: string | null,
  opinions: number,
  metrics: string | null,
  prior_knowledge: string | null,
  software_requirements: string | null,
  schoolId: string | null,
  certificate: string | null,
  professorId: number,
}

export const GET = async (request: NextRequest, response: NextResponse) => {
  try {

    // const professors = [
    //   "Ricardo Celis",
    //   "Enrique Devars",
    //   "Freddy Vega",
    //   "Estefany Aguilar",
    //   "Oscar Barajas Tavares",
    //   "Juan David Castro Gallego",
    //   "Nicolas Molina",
    //   "Carolina Castañeda",
    //   "Carlos Hernández",
    //   "Alfredo Bonilla",
    //   "Juan Sebastián Marulanda",
    //   "Gustavo Grillasca",
    //   "Sebastian Osorio",
    //   "Felipe Pardo",
    //   "Sebastián Leonardo Perez",
    //   "Juan Pablo Castaño Tabares",
    //   "Ernesto García",
    //   "Gerardo López Falcón",
    //   "Patricio López Cerda",
    //   "Diego Mazo",
    //   "Hector Pulido",
    //   "Cristian Zambrano",
    //   "Angela Ocando",
    //   "Team Lemon",
    //   "Mariangel García",
    //   "David Felipe Carvajal",
    //   "Benjamín Isaza",
    //   "Lorena Ortiz",
    //   "Joaquín Moreno",
    //   "Luis Mojica",
    //   "Cristobal Pereira",
    //   "Jazmín Jorquera",
    //   "Sergio Orduz",
    //   "Marcela Valenzuela Gómez",
    //   "Javier Santaolalla",
    //   "Sebastián Rojas",
    //   "Jorge Olavarría",
    //   "Ana Belisa Martínez",
    //   "Diego De Granda",
    //   "Claudio Pinkus",
    //   "Samanta Martínez",
    //   "Rulótico González",
    //   "Estefany Salas",
    //   "Diana Martínez",
    //   "Jonathan Alvarez",
    //   "Eva Ferreira",
    //   "Juliana Gómez",
    //   "Marcelo Arias",
    //   "Blanca Moreno",
    //   "Javier Fuentes Mora",
    //   "Israel Vázquez Morales",
    //   "Alberto Alcocer (Beco)",
    //   "Oswaldo Rodríguez González",
    //   "Platzi Team",
    //   "Adrián Estrada",
    //   "Guido Contreras Woda",
    //   "Mariangélica Useche",
    //   "Samuel Burbano",
    //   "Maria Camila Lenis",
    //   "Ignacio Anaya",
    //   "Jorge Baumann",
    //   "Juan José Torres",
    //   "Abraham Mayo",
    //   "Adán Figueroa Jiménez",
    //   "Carlos Olivera Terrazas",
    //   "Ilse Beatriz Zubieta Martínez",
    //   "Francisco Camacho",
    //   "Sílvia Ariza Sentís",
    //   "Sebastián Sosa",
    //   "Marisol Maldonado",
    //   "Joshua Pedraza",
    //   "Juan Guillermo Gómez Torres",
    //   "Profesor Italo Morales F",
    //   "Willy Aguiar",
    //   "Sandra Carrillo",
    //   "Gastón Bielli",
    //   "Santiago Bernal",
    //   "Pablo Fredrikson",
    //   "David Aroesti",
    //   "Mauro Parra Miranda",
    //   "Amin Espinoza",
    //   "Yamil Asusta",
    //   "Guido Vilariño",
    //   "Gerardo García",
    //   "Ricardo Izquierdo",
    //   "Jorge García",
    //   "Miriam Karina Melgoza",
    //   "Chivas Esports y Avalanche",
    //   "Humberto Cervera",
    //   "Juan Gabriel Gomila",
    //   "Lucio Negrello",
    //   "Francisco Rodríguez Galán",
    //   "Simón Duque",
    //   "Hernán Novillo",
    //   "Jorge Ferretiz",
    //   "Josué Hernández",
    //   "Julián David Méndez",
    //   "Carlos Ávila",
    //   "Harry Villamil",
    //   "Nicolás Mendoza",
    //   "Ama Y Tony",
    //   "Halime Maloof",
    //   "Gabriela Herrera",
    //   "Felipe Martínez Aparicio De la hoz",
    //   "Juan Jáuregui",
    //   "Tati Uribe",
    //   "Maribel Corrales",
    //   "Carolina Gayosso",
    //   "Montserrat Lorente",
    //   "Rodrigo Cortés",
    //   "Jorge Zavala",
    //   "Camila Londoño",
    //   "Sebastián Delmont",
    //   "Carolina Boquín",
    //   "Ricardo Alanís",
    //   "Leomaris Reyes",
    //   "Agustín Navarro Galdon",
    //   "Aníbal Rojas",
    //   "Renzo Cuadra",
    //   "Jhon Carvajal",
    //   "Daniel Torres Burriel",
    //   "Paulina Pimentel",
    //   "Alejandro González",
    //   "Manuel Sescosse",
    //   "Felipe Solem",
    //   "Nat Villegas",
    //   "Trubit Team",
    //   "Miguel Torres",
    //   "Carlos Jahir Carreño",
    //   "Annie Parente Dodero",
    //   "Cristian Ramanzin",
    //   "Ruth Margarita García López",
    //   "Daniel Sánchez Alvarez",
    //   "Orlando Jose Almario Barrios",
    //   "Hederson Carrasquero",
    //   "Josué Ortigoza Ramos",
    //   "Jesús Vélez Santiago",
    //   "Quetzally Meza",
    //   "Isabel Yepes",
    //   "Profesores de Ciberseguridad",
    //   "Diego Ademir Duarte Santana",
    //   "Francisco Daniel Carvajal",
    //   "Donny Alexander Rodríguez Cáceres",
    //   "Juan Pablo Caro",
    //   "Alan J. Baeza",
    //   "Daniel Basulto",
    //   "Herman Marín",
    //   "Daphne S. Leger",
    //   "Álvaro Moya",
    //   "Isabella Arévalo",
    //   "Sthefanni Beltrán",
    //   "Jaime Coll",
    //   "Juliane Butty",
    //   "Alfons Foubert",
    //   "Arantxa Mendoza",
    //   "Zaira García",
    //   "Emilio García",
    //   "Misael León",
    //   "Santiago Camargo",
    //   "Carmen Ansio",
    //   "Verónica Torras",
    //   "Zac Thomas & Manuel Beaudroit",
    //   "Jaime Varela",
    //   "David Flores",
    //   "Elena López Pérez",
    //   "Wilson Sánchez",
    //   "Verónica Traynor",
    //   "Santiago Peña",
    //   "María Daniela Olaya",
    //   "Jennifer Rodríguez Esparza",
    //   "Carlos Alfonso Varón",
    //   "Ekaterina Matveeva",
    //   "Héctor Vega",
    //   "Osmandi Gómez",
    //   "Eduardo Álvarez",
    //   "Bernardo Cassina",
    //   "Luis Martínez",
    //   "Sonia Ardila",
    //   "Carlos Andrés Zambrano Barrera",
    //   "Pamela Márquez",
    //   "Guillermo Martínez",
    //   "Pablo Pérez",
    //   "Antonio Guzmán",
    //   "Nicolas Galagovsky",
    //   "Pablo Reinoso",
    //   "Néstor Escoto",
    //   "Carli Code",
    //   "Natasha Seelam",
    //   "Luis Fernando Laris",
    //   "Layla Scheli",
    //   "Ariel Ortiz",
    //   "María Camila Durango",
    //   "Kevin Sarmiento Mendoza",
    //   "Roy Rojas",
    //   "Giuseppe Vetri",
    //   "Milton Mazzarri",
    //   "Miguel Teheran",
    //   "Sinuhé Jaime Valencia",
    //   "Cristian Villamil",
    //   "Juan Camilo Sandoval",
    //   "Santiago Moreno",
    //   "Alejandra Camacho",
    //   "Carlos Mejía",
    //   "Juan Villalvazo",
    //   "David Bracho",
    //   "Jesús Vargas",
    //   "Daniel James",
    //   "Josecarlos Escobar",
    //   "Xabier Mendoza",
    //   "Jeff Orr",
    //   "Milton Suárez Salazar",
    //   "Santiago Mendoza",
    //   "Alexander Bonilla Rivera",
    //   "Heidy Quitián Lara",
    //   "Karolina Ladino",
    //   "Eduardo Contreras",
    //   "Luis Jorge Novelo",
    //   "Anahí Salgado Díaz de la Vega",
    //   "Ferran Maylinch Carrasco",
    //   "Alejandro Ramírez",
    //   "Guillermo Rodas",
    //   "Mauro Chojrin",
    //   "Sergio Ojeda",
    //   "Héctor Benitez",
    //   "Sergio Estrella",
    //   "Diego Miramontes",
    //   "Eugenio Perea",
    //   "Profes de Habilidades Blandas",
    //   "Ricardo Barra",
    //   "Andrés Salcedo",
    //   "Gerardo Romero",
    //   "Vanessa Amaya",
    //   "César Galicia",
    //   "Beatriz Ibañez",
    //   "Eve Valdes",
    //   "Latinometrics",
    //   "Oksana Yakymchuk",
    //   "Andres Anaya Izasa",
    //   "Diana Lucía Martínez",
    //   "Renzo Roca",
    //   "Manuel Zapata",
    //   "Jorge Villalobos",
    //   "Dra. Aury Curbelo",
    //   "Omar Espejel",
    //   "Adonaí Vera",
    //   "Sergio Paniego Blanco",
    //   "Enrique Alexis Lopez Araujo",
    //   "Ronald Escalona",
    //   "Miguel Ángel Durán",
    //   "Mariandrea Cruz",
    //   "Isis García",
    //   "Fernanda Machado",
    //   "Andrés Moncada",
    //   "NancyNSalazar",
    //   "Maritza Mera",
    //   "Felipe Guzmán",
    //   "Carlos Daniel Sanchez",
    //   "Johan Tique",
    //   "Ana Fernanda Gutierrez Villanueva",
    //   "Jaivic Villegas",
    //   "Camila Ramos",
    //   "Ulises Rayón",
    //   "Mar Ariza-Sentís",
    //   "Julián Cruz",
    //   "Edison Yepes",
    //   "Eric Bellet",
    //   "Juan Camilo Bustamante",
    //   "Profesores de Serverless Framework en AWS",
    //   "Vianel Rodríguez",
    //   "Lupe Canaviri Maydana",
    //   "Wilmer Javier Garzon Cabezas",
    //   "Por",
    //   "Juan Carlos Ruiz",
    //   "Miguel A. Quintero",
    //   "Belen Ceballos",
    //   "David Delgado",
    //   "Juan Pablo Buriticá",
    //   "Luis Antonio Ruvalcaba Sánchez",
    //   "Diana Uribe",
    //   "Daniel Granatta",
    //   "Eduardo Ibarra",
    //   "Martín E. Carrión Ramos",
    //   "Luis Raúl Billy",
    //   "Fabián Oloarte",
    //   "Marina De Giobbi",
    //   "Maria Valeria Chocontá",
    //   "Juan Pablo Ordóñez",
    //   "Ana Karina González",
    //   "Xac León",
    //   "Christian Van Der Henst",
    //   "Julián Rodríguez",
    //   "Ahmed Castro",
    //   "Ana María Díaz Solorio",
    //   "Program Menthors",
    //   "César Fajardo",
    //   "Alberto Pérez-Bermejo",
    //   "Fedosy Santaella",
    //   "Natalia Fainberg",
    //   "Ana María de la Cámara",
    //   "Marcela López",
    //   "Erika Luna",
    //   "Laura Rico",
    //   "Diana Reyes",
    //   "Paula Velandia",
    //   "Camila Barajas Salej",
    //   "Team Platzi",
    //   "Simón Soriano",
    //   "Cristian Daniel Marquez Barrios",
    //   "Álvaro Göede",
    //   "Marta Monterde Alonso",
    //   "Christian Andrade",
    //   "Lucas Forero",
    //   "Juan David Gaines",
    //   "Sebastián Cao",
    //   "Gina Pedraza",
    //   "Jaime Durán",
    //   "René Lora",
    //   "Mariana Lafón",
    //   "Vicky Peña",
    //   "César Cordero",
    //   "Jess Harris",
    //   "Lina Carrascal",
    //   "Ravee Lakhmani",
    //   "Romany Dear",
    //   "Mayra K. Triana",
    //   "Christopher Edenfield",
    //   "Aileen Hale",
    //   "Caterina Barbosa",
    //   "Cole McCannon",
    //   "Sarah Roecklein",
    //   "Kyra Sage",
    //   "Andrés Blanco",
    //   "Seyma Anajafi",
    //   "Julian Bernal",
    //   "English Academy",
    //   "Michelle Easley",
    //   "Austin Snyder",
    //   "Itzel González",
    //   "Esteban Ocompley",
    //   "Natalia Durango",
    //   "Lina Ramírez",
    //   "Carlos Arango",
    //   "Yaiza Velázquez",
    //   "Daniela Belén González",
    //   "Agostina Ardenghi",
    //   "Mari Fernández",
    //   "Juan Tamayo",
    //   "Laura Duarte",
    //   "Andrés Londoño",
    //   "Nicole Chapaval",
    //   "Daniel Patiño",
    //   "Carlos van Oosterzee",
    //   "Carolina Di Marco",
    //   "Ximena Hernández",
    //   "Rosa Morel",
    //   "Jonah Berger",
    //   "Clau Alderete",
    //   "Ismael Briasco",
    //   "Paula Andrea Gaviria",
    //   "Natalia Prieto",
    //   "Catherine Hernández",
    //   "Alina Poulain",
    //   "Nubia Mary Varón",
    //   "Pablo Lomeli",
    //   "Diego Barrazas",
    //   "Joaquín Loyo",
    //   "Mónica Salazar Zuluaga",
    //   "Felipe Ríos Barraza",
    //   "Alejandro González & Iván Ramos",
    //   "Ricardo Mendoza Castro",
    //   "Emilio Miguel López",
    //   "Luisa Acelas",
    //   "Juan José Bello",
    //   "Daniel Murcia",
    //   "Irving Calderon",
    //   "Rolando González",
    //   "Aumentados",
    //   "Janet Machuka",
    //   "Ana Agudelo",
    //   "Jennifer Vega",
    //   "Luis Carlos Ávila",
    //   "María Victoria Navarro",
    //   "Sharon Flores",
    //   "Sergio Aristizábal",
    //   "Diana Zalaquett",
    //   "Daniela Estefanía Gómez De Almada",
    //   "Carlos Trujillo",
    //   "Juan Pablo Rojas",
    //   "Javier Castro Rueda",
    //   "Humberto Amador",
    //   "Pamela Valdés",
    //   "Martha Muñoz",
    //   "Julieta Zambelli",
    //   "Florian Raetzer",
    //   "Barrack Onyango",
    //   "Ingrid Zúñiga",
    //   "Jonathan Zamacona",
    //   "Alejandra Morales Teo",
    //   "Paula Riveros Tovar",
    //   "María Fornieles",
    //   "Diego Pinzón",
    //   "Alexandra Barrero",
    //   "Juan Felipe Peralta",
    //   "Santiago Sánchez Suarez",
    //   "Carlos Céspedes",
    //   "Nayar Cast'Alpha",
    //   "Paola Albornoz Fernández",
    //   "Ruben Gomez",
    //   "Belen Paoletti",
    //   "Leonel Hernández",
    //   "Pilar Delgado",
    //   "Pablo Cíntora",
    //   "Carolina Bautista",
    //   "Kim De Anda",
    //   "María Isabel Ramírez",
    //   "Diana Salej",
    //   "Luciano Dal Maso",
    //   "João Barroso",
    //   "Juliana de Carvalho",
    //   "Andrea Alessio",
    //   "Piolo Juvera",
    //   "Sam Osbourne",
    //   "María Posa",
    //   "Nadia Michelle",
    //   "Mariana Figueiredo",
    //   "Jorge Rabaso",
    //   "Miguel Lardizábal",
    //   "Katherine Guio",
    //   "Bolivar Verbel",
    //   "Daniel Sánchez",
    //   "Camila Pardo",
    //   "Mónica Mayén",
    //   "Camilo Gómez",
    //   "Marian Villa",
    //   "Laura Montealegre Moreno",
    //   "Jaime Daza",
    //   "Dianita Páez",
    //   "Marcos Algorta",
    //   "Ana Gisbert Martin de Hijas",
    //   "Bernardo Torres",
    //   "Liliana Zamacona",
    //   "Valeria D'Amato",
    //   "Virginia Campo",
    //   "Gissela Peralta",
    //   "Liliana Olivares Gómez",
    //   "Juan Camilo González",
    //   "Pamela Castro",
    //   "Santiago Estrada",
    //   "Ricardo Adolfo Velásquez Ordoñez",
    //   "Isis Alexandra Rivera",
    //   "Esteban Usandizaga",
    //   "Juan Alberto González",
    //   "Andrea Velásquez",
    //   "Ana Magaly Reyes Hill",
    //   "Jose Orlando Morera",
    //   "Nicolás Poveda",
    //   "Daniel Cáceres Apolaya",
    //   "José Iván Anaya",
    //   "Ivannia Murillo",
    //   "Madres Platzi",
    //   "Alba Reyes",
    //   "Sugey Valois",
    //   "Sandra Escobar",
    //   "Ophelia Pastrana",
    //   "Graciela Sandoval Aguilar",
    //   "Nicko Nogués",
    //   "Dostin Hurtado",
    //   "Mario García",
    //   "Jorge Moreno",
    //   "José Daniel Huérfano",
    //   "Tomás Gómez González",
    //   "Mario Valle",
    //   "Ariel Mamani",
    //   "Diana Ramos",
    //   "Natalia Usme",
    //   "Alba Crivillé",
    //   "Equipo Negocios desde Cero",
    //   "Victor Servín",
    //   "Lizet Padilla Barragán",
    //   "Javier Cifuentes",
    //   "Alberto Samaniego",
    //   "Natalia Osorio",
    //   "Adriana Prieto",
    //   "Tali Shaouly",
    //   "Jorge Rabaso y Claudio Pinkus",
    //   "Alejandro García",
    //   "Alexis Acuña",
    //   "Silvia Marín",
    //   "Layon Costa",
    //   "Bernardo Martinez Romero",
    //   "Giulia Ducci",
    //   "Ricardo Flores",
    //   "Marco Medina",
    //   "Juan del Cerro",
    //   "Jenny González, Pedro Díaz y Alejandro Kratc",
    //   "Jorge Ranni (Georgie)",
    //   "Elena Madrigal",
    //   "Equipo HubSpot",
    //   "José Tomás Lobo",
    //   "Daniel Salinas",
    //   "Oriana Mazón",
    //   "Julián Caviedes",
    //   "Raquel Mosquera",
    //   "Brandon Kaufmann",
    //   "Joaquín Stephens",
    //   "Álvaro Castro",
    //   "Marisol Menéndez",
    //   "Santiago Zavala",
    //   "Tuto Assad",
    //   "Tiago Sada",
    //   "Kevin Hale",
    //   "Damaris Mendoza",
    //   "Axel Romero",
    //   "Sebastián Zuluaga Valencia",
    //   "Emiro Arrieta",
    //   "Felipe Calderón",
    //   "Tino Nájera",
    //   "Daniela González",
    //   "Carlos Jiménez",
    //   "Erick Ortega",
    //   "Maria Elena Manero",
    //   "Nadim José Amin De La Hoz",
    //   "Sara Jotabé",
    //   "Guillermo García",
    //   "Santiago Méndez",
    //   "Adrian Solca",
    //   "Cinta Vergés",
    //   "Juliana Buitrago",
    //   "Tomás Nicolini",
    //   "Ricardo Mendi",
    //   "María Isabel Murillo",
    //   "Emiliano Cosenza",
    //   "Liz Nenning",
    //   "Juani Ruiz Echazú",
    //   "meri Fernández",
    //   "Mariana Aristizábal",
    //   "Sergio Nouvel",
    //   "Miguel Ángel Torres",
    //   "Grecia Omaña",
    //   "Ethan Parry",
    //   "Julio Servan",
    //   "Lina María Arias",
    //   "Veronica Espindola",
    //   "Laura Rojas Aponte",
    //   "Carlos Sanabria",
    //   "Félix Riaño",
    //   "Melanie Tobal",
    //   "Matías Carvajal García",
    //   "Piedad Mora",
    //   "Gustavo Kurlat",
    //   "Production Team",
    //   "Diana Ancines",
    //   "Nicolás Bello",
    //   "Nicolay Coral",
    //   "Felipe Cardona",
    //   "Erika Oregel",
    //   "Paola Piñón Mazlum",
    //   "Anna Grajales",
    //   "Vanessa Parra",
    //   "Diego Narciso",
    //   "Pepe Rodelo",
    //   "Daniel Carvajal N",
    //   "Juan Felipe Ríos",
    //   "Tamara Blázquez",
    //   "Leo Felipe Campos",
    //   "Edna Cárdenas",
    //   "Luz Lancheros",
    //   "Linda Patiño",
    //   "Javier Matuk",
    //   "Verónica Calderón"
    // ]

    let { data: courses, error } = await supabase
      .from('Courses')
      .select(`
        id,
        title,
        badge_url,
        professor,
        first_class,
        landing_url,
        duration,
        created_at,
        description,
        date,
        level,
        practice_time,
        opinions_link,
        opinions,
        metrics,
        prior_knowledge,
        software_requirements,
        schoolId,
        certificate,
        professorId
      `)

    // console.log('data', data?.length)

    let { data: professors, error: error2 } = await supabase
      .from('Professors')
      .select(`
      id,
      name
    `)

    const filteredCourses = courses?.filter(({ professorId }) => !professorId)

    return Response.json({ filteredCourses })


    // const professors = [...new Set(courses?.map(({ professor }) => professor))]

    // if (courses && professors) {
    //   const updatedCourses = courses.map(({ professor, ...rest }) => {
    //     return {
    //       ...rest,
    //       professor,
    //       professorId: professors.find((item) => item.name === professor)?.id || null
    //     }
    //   })
    //   console.log('updatedCourses', updatedCourses.length)
    //   for (const course of updatedCourses) {
    //     const index = updatedCourses.findIndex(({ id }) => course.id === id)
    //     try {
    //       const { data, error } = await supabase
    //         .from('Courses')
    //         .update(course)
    //         .eq("id", course.id)

    //       if (error) {
    //         console.log(error);
    //       } else {
    //         console.log(`Curso ${index} actualizado: ${course.landing_url}`)
    //       }

    //     } catch (error) {
    //       console.log('error', error)
    //       console.log(`Error al actualizar curso: ${course.id}`)
    //     }
    //   }
    //   return Response.json({ updatedCourses })
    // }

    // if (professors) {

    //   const missingProfessors = professors.filter((professor) => {
    //     return !professors.find((item) => item.name === professor)
    //   })

    //   return Response.json({
    //     missingProfessors,
    //     professorsTable: professors.length
    //   })
    // }

  } catch (error) {
    return Response.json({ message: "There has been a server error" })
  }
}
